# ======================================================
#             NoCrystalTNT - Konfiguracja
# ======================================================

settings:
  disable-crystal-explosions: true       # Blokuje wybuchy End Crystali
  remove-crystal-on-hit: true            # Po uderzeniu Crystal po prostu znika (bez wybuchu)
  
  disable-tnt-minecart-explosions: true  # Blokuje wybuchy wagoników z TNT
  remove-tnt-minecart-on-hit: false      # Czy uderzenie TNT Minecarta ma go po prostu usunąć
